(SimpleDomain TestSimpleHybridPlanningDomain)
(Controllable RobotProprioception) #proprioception
(Controllable atLocation) #tabletop perception
(Resource arm  2)
(Resource fieldOfView 200)
(Resource robot1 1)
(Resource manArea 1)
(Resource arm1 1)
(Resource arm2 1)

(SimpleOperator  
 (Head RobotAction::ask_human_to_reachable_cup1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
 (RequiredResource fieldOfView(200)) 
)
(SimpleOperator  
 (Head RobotAction::ask_human_to_reachable_book1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
 (RequiredResource fieldOfView(200)) 
)
(SimpleOperator  
 (Head RobotAction::ask_human_to_reachable_monitor1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
 (RequiredResource fieldOfView(200)) 
)
(SimpleOperator  
 (Head RobotAction::ask_human_to_reachable_keyboard1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
 (RequiredResource fieldOfView(200)) 
)
(SimpleOperator  
 (Head RobotAction::ask_human_to_reachable_pen1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
 (RequiredResource fieldOfView(200)) 
)
(SimpleOperator  
 (Head RobotAction::ask_human_to_reachable_notebook1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
 (RequiredResource fieldOfView(200)) 
)
(SimpleOperator  
 (Head RobotAction::ask_human_to_reachable_penHolder1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
 (RequiredResource fieldOfView(200)) 
)
(SimpleOperator  
 (Head RobotAction::moveTo_manipulationArea_cup1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotAction::moveTo_manipulationArea_book1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotAction::moveTo_manipulationArea_monitor1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotAction::moveTo_manipulationArea_keyboard1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotAction::moveTo_manipulationArea_pen1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotAction::moveTo_manipulationArea_notebook1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotAction::moveTo_manipulationArea_penHolder1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_cup1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_cup1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_cup1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_cup1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_book1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_book1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_book1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_book1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_monitor1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_monitor1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_monitor1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_monitor1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_keyboard1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_keyboard1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_keyboard1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_keyboard1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_pen1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_pen1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_pen1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_pen1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_notebook1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_notebook1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_notebook1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_notebook1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_penHolder1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_penHolder1_table1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_picking_penHolder1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
(SimpleOperator  
 (Head RobotSense::sensing_before_placing_penHolder1_tray1()) 
 (RequiredState req1 atLocation::at_robot1_table1()) 
 (Constraint During(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource fieldOfView(200))  
 (RequiredResource robot1(1))  
)
#######################################################
(SimpleOperator  
 (Head atLocation::at_cup1_table1()) 
 (RequiredState req1 RobotAction::place_cup1_arm1__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head atLocation::at_cup1_table1()) 
 (RequiredState req1 RobotAction::place_cup1_arm2__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head RobotAction::place_cup1_arm1__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm1_cup1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_cup1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_cup1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::place_cup1_arm2__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm2_cup1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_cup1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_cup1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm1_cup1()) 
 (RequiredState req1 RobotAction::pick_cup1_arm1__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm2_cup1()) 
 (RequiredState req1 RobotAction::pick_cup1_arm2__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_cup1_arm1__table1()) 
 (RequiredState req1 atLocation::at_cup1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_cup1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_cup1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_cup1_arm2__table1()) 
 (RequiredState req1 atLocation::at_cup1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_cup1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_cup1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
#######################################################
#######################################################
(SimpleOperator  
 (Head atLocation::at_book1_table1()) 
 (RequiredState req1 RobotAction::place_book1_arm1__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head atLocation::at_book1_table1()) 
 (RequiredState req1 RobotAction::place_book1_arm2__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head RobotAction::place_book1_arm1__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm1_book1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_book1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_book1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::place_book1_arm2__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm2_book1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_book1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_book1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm1_book1()) 
 (RequiredState req1 RobotAction::pick_book1_arm1__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm2_book1()) 
 (RequiredState req1 RobotAction::pick_book1_arm2__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_book1_arm1__table1()) 
 (RequiredState req1 atLocation::at_book1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_book1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_book1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_book1_arm2__table1()) 
 (RequiredState req1 atLocation::at_book1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_book1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_book1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
#######################################################
#######################################################
(SimpleOperator  
 (Head atLocation::at_monitor1_table1()) 
 (RequiredState req1 RobotAction::place_monitor1_arm1__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head atLocation::at_monitor1_table1()) 
 (RequiredState req1 RobotAction::place_monitor1_arm2__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head RobotAction::place_monitor1_arm1__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm1_monitor1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_monitor1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_monitor1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::place_monitor1_arm2__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm2_monitor1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_monitor1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_monitor1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm1_monitor1()) 
 (RequiredState req1 RobotAction::pick_monitor1_arm1__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm2_monitor1()) 
 (RequiredState req1 RobotAction::pick_monitor1_arm2__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_monitor1_arm1__table1()) 
 (RequiredState req1 atLocation::at_monitor1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_monitor1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_monitor1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_monitor1_arm2__table1()) 
 (RequiredState req1 atLocation::at_monitor1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_monitor1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_monitor1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
#######################################################
#######################################################
(SimpleOperator  
 (Head atLocation::at_keyboard1_table1()) 
 (RequiredState req1 RobotAction::place_keyboard1_arm1__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head atLocation::at_keyboard1_table1()) 
 (RequiredState req1 RobotAction::place_keyboard1_arm2__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head RobotAction::place_keyboard1_arm1__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm1_keyboard1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_keyboard1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_keyboard1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::place_keyboard1_arm2__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm2_keyboard1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_keyboard1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_keyboard1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm1_keyboard1()) 
 (RequiredState req1 RobotAction::pick_keyboard1_arm1__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm2_keyboard1()) 
 (RequiredState req1 RobotAction::pick_keyboard1_arm2__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_keyboard1_arm1__table1()) 
 (RequiredState req1 atLocation::at_keyboard1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_keyboard1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_keyboard1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_keyboard1_arm2__table1()) 
 (RequiredState req1 atLocation::at_keyboard1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_keyboard1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_keyboard1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
#######################################################
#######################################################
(SimpleOperator  
 (Head atLocation::at_pen1_table1()) 
 (RequiredState req1 RobotAction::place_pen1_arm1__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head atLocation::at_pen1_table1()) 
 (RequiredState req1 RobotAction::place_pen1_arm2__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head RobotAction::place_pen1_arm1__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm1_pen1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_pen1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_pen1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::place_pen1_arm2__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm2_pen1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_pen1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_pen1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm1_pen1()) 
 (RequiredState req1 RobotAction::pick_pen1_arm1__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm2_pen1()) 
 (RequiredState req1 RobotAction::pick_pen1_arm2__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_pen1_arm1__table1()) 
 (RequiredState req1 atLocation::at_pen1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_pen1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_pen1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_pen1_arm2__table1()) 
 (RequiredState req1 atLocation::at_pen1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_pen1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_pen1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
#######################################################
#######################################################
(SimpleOperator  
 (Head atLocation::at_notebook1_table1()) 
 (RequiredState req1 RobotAction::place_notebook1_arm1__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head atLocation::at_notebook1_table1()) 
 (RequiredState req1 RobotAction::place_notebook1_arm2__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head RobotAction::place_notebook1_arm1__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm1_notebook1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_notebook1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_notebook1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::place_notebook1_arm2__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm2_notebook1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_notebook1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_notebook1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm1_notebook1()) 
 (RequiredState req1 RobotAction::pick_notebook1_arm1__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm2_notebook1()) 
 (RequiredState req1 RobotAction::pick_notebook1_arm2__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_notebook1_arm1__table1()) 
 (RequiredState req1 atLocation::at_notebook1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_notebook1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_notebook1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_notebook1_arm2__table1()) 
 (RequiredState req1 atLocation::at_notebook1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_notebook1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_notebook1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
#######################################################
#######################################################
(SimpleOperator  
 (Head atLocation::at_penHolder1_table1()) 
 (RequiredState req1 RobotAction::place_penHolder1_arm1__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head atLocation::at_penHolder1_table1()) 
 (RequiredState req1 RobotAction::place_penHolder1_arm2__table1()) 
 (Constraint StartedBy(Head,req1)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
)
(SimpleOperator  
 (Head RobotAction::place_penHolder1_arm1__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm1_penHolder1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_penHolder1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_penHolder1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::place_penHolder1_arm2__table1()) 
 (RequiredState req1 RobotProprioception::holding_arm2_penHolder1()) 
 (RequiredState req2 RobotSense::sensing_before_placing_penHolder1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_penHolder1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm1_penHolder1()) 
 (RequiredState req1 RobotAction::pick_penHolder1_arm1__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotProprioception::holding_arm2_penHolder1()) 
 (RequiredState req1 RobotAction::pick_penHolder1_arm2__table1()) 
 (Constraint MetBy(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource arm2(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_penHolder1_arm1__table1()) 
 (RequiredState req1 atLocation::at_penHolder1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_penHolder1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_penHolder1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm1(1)) 
)
(SimpleOperator  
 (Head RobotAction::pick_penHolder1_arm2__table1()) 
 (RequiredState req1 atLocation::at_penHolder1_table1()) 
 (RequiredState req2 RobotSense::sensing_before_picking_penHolder1_table1()) 
 (RequiredState req3 atLocation::at_robot1_table1()) 
 (RequiredState req4 atLocation::at_robot1_manipulationArea_penHolder1_table1()) 
 (Constraint During(Head,req4)) 
 (Constraint During(req2,req3)) 
 (Constraint During(Head,req3)) 
 (Constraint MetBy(Head,req2)) 
 (Constraint OverlappedBy(Head,req1)) 
 (Constraint Finishes(Head,req1)) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource arm(1)) 
 (RequiredResource fieldOfView(1)) 
 (RequiredResource robot1(1)) 
 (RequiredResource arm2(1)) 
)
#######################################################
(SimpleOperator  
 (Head atLocation::at_robot1_manipulationArea_cup1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource manArea(1))  
)
(SimpleOperator  
 (Head atLocation::at_robot1_manipulationArea_book1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource manArea(1))  
)
(SimpleOperator  
 (Head atLocation::at_robot1_manipulationArea_monitor1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource manArea(1))  
)
(SimpleOperator  
 (Head atLocation::at_robot1_manipulationArea_keyboard1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource manArea(1))  
)
(SimpleOperator  
 (Head atLocation::at_robot1_manipulationArea_pen1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource manArea(1))  
)
(SimpleOperator  
 (Head atLocation::at_robot1_manipulationArea_notebook1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource manArea(1))  
)
(SimpleOperator  
 (Head atLocation::at_robot1_manipulationArea_penHolder1_table1()) 
 (Constraint Duration[2000,INF](Head)) 
 (RequiredResource manArea(1))  
)

